### ISSUE TITLE
Project build failing using `gowebly create` on `bun run build`

### ISSUE THREAD

**Issue by jacktrusler** [gowebly/gowebly#92]
**Required check list:**

- [ x] I didn't find in the repository's issues section a similar bug.
- [x ] I understand, this is an Open Source and not-for-profit product.
- [ x] This is not about a third-party project, framework, or technology.

**My environment:**

```
✓ Your system information has been collected successfully!

│
│ Copy this information to paste into an issue ↘
│
│ Gowebly CLI: v2.6.3 (build with go1.22.4 on darwin/arm64)
│
│ Go: 1.22.0 darwin/arm64
│ Node.js version: 22.1.0 (npm 10.7.0)
│ Bun version: 1.1.20
│
│ Is Air tool installed? true
│ Is Templ package installed? true
│

✱ For more information go to the official docs: https://gowebly.org
```
...

**Describe the bug:**

The build fails after installing nearly almost all the folder and files needed, but cannot run `bun run build`, when I look in the `package.json`, there's no auto generated build script. This is remedied by adding 

```
"scripts": {
    "build": "parcel build"
  },
```
To my package.json
...

**Steps to reproduce the behavior:**

1. gowebly create
2. follow steps
3. fails on `bun run build`

**Expected behavior:**

Project builds with no errors
...

**Screenshots:**

![CleanShot 2024-07-17 at 09 59 15](https://github.com/user-attachments/assets/7f2b3d58-ab80-4617-a9ae-7ea911a9f744)

**Comment by koddr** [comment]
Hi, @jacktrusler

Can you please enter the name of the repo & package without underscore char? Maybe this broke the package.json

**Comment by jacktrusler** [comment]
Same problem. 

![CleanShot 2024-07-17 at 11 15 46](https://github.com/user-attachments/assets/ff25ea13-864b-473c-bb33-e14f04b87e91)

**Comment by koddr** [comment]
It's really strange. 

Here is my demo for today: https://youtu.be/57xnlTS2tnM?si=8JHGURuMQh2F8osV

**Comment by jacktrusler** [comment]
No worries, it might be a package problem on my end, i'll try making a minimal environment and trying again.

**Comment by koddr** [comment]
@jacktrusler fixed in `v2.6.5`.

Please check this Gowebly CLI version on your end 😉

**Comment by jacktrusler** [comment]
Hey, thanks for the effort, it still doesn't work on my Mac (Sonoma 14.3.1), I made a fedora 40 docker container to try a minimal environment and it worked fine *with bun*. No clue what the problem could be, but when I try it without bun on MacOS it succeeds, when i try it with bun it fails. I honestly don't care to use bun, so this is no problem for me. But just following up in case you run into this problem later. 

![CleanShot 2024-07-25 at 14 32 54](https://github.com/user-attachments/assets/b85d41b6-fb5f-46db-9eef-d777557350fd)

**Comment by koddr** [comment]
> Here is my demo for today: https://youtu.be/57xnlTS2tnM?si=8JHGURuMQh2F8osV

@jacktrusler the video that I posted above was just shot on my working machine with macOS Sonoma 14.5 (23F79).

Maybe `bun` (or `gowebly`) process doesn't have execution rights in your system?

Please try the same thing, but via `sudo`.
